export const Countries = {
  UNITED_STATES: 'UNITED_STATES',
  ANTIGUA_AND_BARBUDA: 'ANTIGUA_AND_BARBUDA',
  DOMINICA: 'DOMINICA',
  GRENADA: 'GRENADA',
  ST_KITTS_AND_NEVIS: 'ST_KITTS_AND_NEVIS',
  ST_LUCIA: 'ST_LUCIA',
  ST_VINCENT_AND_THE_GRENADINES: 'ST_VINCENT_AND_THE_GRENADINES',
};
